### ISSUE TITLE
Include Administrator permission by default

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Labs/islandora_simple_map#1]
Administrator is not given permission by default to configure the module, and the configure option does not appear in admin menu until the permission is checked off. Permission should be granted by default, or should accept administrator permissions bypass.

**Comment by mjordan** [comment]
Good catch. Would "administer site configuration" be OK?

**Comment by mjordan** [comment]
Rereading this, I don't think I understand. The "administer site configuration" is already there, and the module doesn't implement any permissions on its own, so I think I need some additional information/clarification. Which permission are you checking off?

**Comment by bondjimbond** [comment]
I don't know -- it looks different now (since the last commits?). But in order to view the config screen (or even the config option) I had to find Islandora Simple Map (or possibly some other heading) in the Permissions and check something off. Permission is gone now.

**Comment by mjordan** [comment]
Not sure what's what. Clearing the cache would have cleared up any menu-related funniness. If you can't replicate the problem, go ahead and close this issue, and if it recurs, you can reopen it or create an new one.
