### ISSUE TITLE
Map scrolling is distracting - add option to disable

### ISSUE THREAD

**Issue by rosiel** [Islandora-Labs/islandora_simple_map#11]
When scrolling down a site, hitting the map means the map scrolls instead of the page.

I would use an option to disable scrolling altogether (or click-to-enable scrolling) - would this be welcome?

**Comment by mjordan** [comment]
@rosiel, I'm not sure what you're describing. Would it be asking too much for you to create a simple video/screencast illustrating the problem? Regardless, if you can add a config option to address the problem, and the option doesn't have any side effects when "off", I'd be happy to accept a pull request.

**Comment by MarcusBarnes** [comment]
I believe @rosiel is referring to providing an option to set the scrollwheel option to false.  According to https://developers.google.com/maps/documentation/javascript/reference it defaults to true.    If the user is scrolling down the page and the mouse goes over a Google map with scrollwheel as true, the map starts zooming when scrolling.

**Comment by mjordan** [comment]
Unfortunately, this module doesn't use the Maps Javascript API, so that option wouldn't apply.

**Comment by rosiel** [comment]
@MarcusBarnes that's what I'm talking about! Here's a screencast [1]. But @mjordan is right that we can't just scrollwheel=false; this uses the embed api, and there are ways around this - for instance the workarounds documented in [2]. 

[1] https://www.dropbox.com/s/4zda0fo8c3ly1ky/scrolling.mov?dl=0
[2] http://stackoverflow.com/questions/21992498/disable-mouse-scroll-wheel-zoom-on-embedded-google-maps

**Comment by mjordan** [comment]
@rosiel if you want to implement an option that uses the solution you propose, please go ahead and open a PR. I'd prefer to make the default behavior consistent with the current scrolling, if only to avoid changing existing installations. Is that OK?

**Comment by whikloj** [comment]
@rosiel this is now an option, if you would check it out and see if it solves your use case and if so, close this ticket.

**Comment by rosiel** [comment]
Solved! Thanks!
