### ISSUE TITLE
Not working for Book CModel?

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Labs/islandora_simple_map#12]
We have Islandora Simple Map enabled on several sites in Arca, and while it works perfectly well on Basic and Large Images, the map does not display on Book objects. 

Example: http://arcabc.ca/islandora/object/ufv%3A378

Configuration is with the following XPaths:
```
//mods:subject/mods:cartographics/mods:coordinates
//mods:subject/mods:geographic
//mods:subject/mods:hierarchicalGeographic
```
Metadata is present in each of the above elements, but no map is generated.

**Comment by mjordan** [comment]
#8 addressed a problem with the book cmodel. Can you confirm you are running the latest version of this module (or at least a version that contains commit 3cee3833614e53a207696a4cb3b24ac0f9d9e931)?

**Comment by bondjimbond** [comment]
Just confirmed - I'm running the latest version.

**Comment by mjordan** [comment]
OK, thanks. Would you mind creating a test object (say a basic image) that uses the same MODS datastream as the problematic book and seeing if the map renders?

**Comment by bondjimbond** [comment]
Ack, sorry; just realized that the object I was using was the wrong one. Updating to latest version does indeed fix the problem.

**Comment by mjordan** [comment]
Excellent! (that there is no issue, that is). Thanks for closing.
