### ISSUE TITLE
Make this a block?

### ISSUE THREAD

**Issue by whikloj** [Islandora-Labs/islandora_simple_map#13]
Hello @mjordan, I am back to steal more of your wonderful code.

We are migrating a Public Art project, which I built using HTML and javascript many years ago. http://umanitoba.ca/libraries/units/archfa/art_tour/

My idea is to have a map on the collection page that aggregates the points from the items in the collection. For this I thought a block might be better.

I'm gonna fork this and I'll try to not move to far away from your existing implementation.

**Comment by mjordan** [comment]
@whikloj I agree that there should be a "render in block" option or similar for this module. That would be awesome.

To plot data on a map you will likely need to use the proper Google Maps API. There was some discussion in #7 on this, but I hit a [roadblock](https://github.com/mjordan/islandora_simple_map/issues/7#issuecomment-230298439) that you may be able to overcome.

There are alternatives to this module that you should check out:

* https://github.com/jyobb/islandora_map_browse
  * Plots multipoint data on a map
* https://github.com/discoverygarden/islandora_gmap
  * Alows GeoJSON data or KML documents to be rendered on a map

**Comment by whikloj** [comment]
Those are good modules too, but neither has a block option nor a collection display. So if you are ok with me making some changes I'll see what I can get to work in my fork.

**Comment by mjordan** [comment]
Totally, but please make you changes optional so existing installs don't break.

**Comment by whikloj** [comment]
👍

**Comment by whikloj** [comment]
I have a block working with Google Maps API, I also added the disable scroll wheel zoom referenced in https://github.com/mjordan/islandora_simple_map/issues/11

![simple_map_api](https://user-images.githubusercontent.com/2857697/28634969-85117752-71fe-11e7-9bca-84112349101a.jpg)

This is a super simple version, using CSS to set the box size. Probably could use some tidying.

**Comment by mjordan** [comment]
@whikloj very nice, I'll do a smoketest later today.

**Comment by mjordan** [comment]
... but I can't find your forked repo. Ping me when you're ready!

**Comment by whikloj** [comment]
@mjordan sorry its under the University group, I should stop switching back and forth.
https://github.com/uml-digitalinitiatives/islandora_simple_map

**Comment by whikloj** [comment]
Ok, I found a problem. You can't have the block on the same page as the normal page alter map. I'll play with that.

**Comment by mjordan** [comment]
I think it's reasonable that the admin would need to choose one or the other.

**Comment by whikloj** [comment]
Ok, so then I would need to add a toggle to allow you to disable the map on the page if you have selected to use the Google Maps API.

**Comment by mjordan** [comment]
I can't think of a situation where you'd want both the page alter map and a block with the same content on the same page. How much effort is required to add a toggle? If we want the admin form to respond to the toggle (e.g. only show the options that apply) I can do that work with `#states` after we merge your PR, if that reduces the amount of work you'd need to do.

**Comment by whikloj** [comment]
Ok, I have made the page and block maps both work together. Or at least they do on my machine. Basically each sends its own config with its map holder id and then they can be processed. 

I still don't know if you'd want a page and block map to display together...but now they won't break, they'll just be redundant. 

I'll add a simple toggle to turn off the page display. So if you add the block you can choose to have both or only one.

**Comment by whikloj** [comment]
Resolved with https://github.com/mjordan/islandora_simple_map/commit/7ccd9d47df3c5c3bfe47c2dbe78c41054652e71d
