### ISSUE TITLE
Why is clean up replacing semi-colons with commas?

### ISSUE THREAD

**Issue by whikloj** [Islandora-Labs/islandora_simple_map#16]
Meta-issue arising [here](https://github.com/mjordan/islandora_simple_map/issues/6#issuecomment-318392577).

In the code you can (and by [default do](https://github.com/mjordan/islandora_simple_map/blob/7.x/islandora_simple_map.module#L71)), replace semi-colons with commas in the node values found in the MODS.
https://github.com/mjordan/islandora_simple_map/blob/7.x/islandora_simple_map.module#L157-L169

Why are we doing this? 
Did someone have semi-colons instead of commas in their metadata?

**Comment by mjordan** [comment]
Not that I recall. I have no idea what the specific reason I added that was. I like your idea of getting more info on what people are doing before we remove any features though, if that's OK. I can send a message out to the list.

**Comment by mjordan** [comment]
OK, request for feedback, with end date of "early next week", [posted to the Islandora group](https://groups.google.com/d/msgid/islandora/790480090.3454620.1501189935690.JavaMail.zimbra%40sfu.ca?utm_medium=email&utm_source=footer).

**Comment by mjordan** [comment]
Some examples, from MODS:

Two points in one element, delimited with a semicolon:

```xml
<subject>
  <cartographics>
    <coordinates>+51.585,-124.71722; +51.52333,-124.97861</coordinates>
  </cartographics>
</subject>
```
Same two points in one element, each in a separate element:

```xml
<subject>
  <cartographics>
    <coordinates>+51.585,-124.71722</coordinates>
  </cartographics>
  <cartographics>
    <coordinates>+51.52333,-124.97861</coordinates>
  </cartographics>
</subject>
```

```

**Comment by jyobb** [comment]
The islandora_map_browse module I created has configurable mods fields for location data. I set it up to use a comma (lat, long). However, I was asked to modify the module to also support separate lat/long fields. See the issue here: https://github.com/jyobb/islandora_map_browse/issues/11

At the UofS we use lat,long exclusively.

**Comment by mjordan** [comment]
Thanks John, similar problem. Just to summarize the difference between John's Islandora Map Browse module and Islandora Simple Map, his shows search results on a map, whereas this one extracts geocoordinates from a datastream and displays the resulting map in the object display.

**Comment by whikloj** [comment]
@jyobb Thanks for the information.  @mjordan had already implemented a similar solution of a textfield for entering various XPaths to search. Now with the Google Maps Javascript API we are able to follow all of those XPaths and collect the various points. 

I was more trying to understand why there was an option to convert `;` -> `,`

I can understand why it would be done, but with us now thinking about using `;` as the delimiter between multiple coordinates, stripping it out has implications.

However I will be looking through your code as I want to add a Solr component to allow a Collection to display a map with all the points from the objects in that collection. 👍

**Comment by mjordan** [comment]
> However I will be looking through your code as I want to add a Solr component to allow a Collection to display a map with all the points from the objects in that collection. 

Nice.

**Comment by uconnjeustis** [comment]
Here are some examples of MODS we did at different times with different project leads. I had to change the ext. to txt to copy it here. 

The first one is form our GIS collection and contains the bounding box information.
[uconn_asc_1998-0378_map_5_28_13.txt](https://github.com/mjordan/islandora_simple_map/files/1184062/uconn_asc_1998-0378_map_5_28_13.txt)

This one just has center point in degrees.
[MODS Record (1).txt](https://github.com/mjordan/islandora_simple_map/files/1184054/MODS.Record.1.txt)

If you need more examples, I can did those up. Before we asked that everyone use decimal, people tended to use degrees sometimes with delimiters for the center point or not.
Jennifer

**Comment by whikloj** [comment]
@uconnjeustis so would it be useful to have a way to add different coordinate systems? Sometimes it is more trouble to allow people to add it in any format, but would that be useful?

Additionally, I have thought about adding a hook to get coordinates. So you could write your own function to fit with whatever your various data might be and convert them into standard decimal for Google?

**Comment by mjordan** [comment]
👍 to providing a hook to get coordinates. That would let module writers accommodate any local practice.

**Comment by whikloj** [comment]
New hook issue - https://github.com/mjordan/islandora_simple_map/issues/18

**Comment by mjordan** [comment]
Since the hook is now in place, can we close this? Will doing so break anyone's maps?

**Comment by whikloj** [comment]
I guess we can close this, mostly I'm still interested if anyone is still using the `cleanup` option. 

Mostly because that option only converts `;` to `,`. It has a very narrow scope and the README suggests that `;` be used for delineating multiple coordinates.

But as the cleanup option has been around for awhile and the multiple coordinate delimiter can be set to anything. I guess we should close this and just leave that option in place for now.

Maybe it should be deprecated in the future, or we can add some logic to not allow a multiple coordinate delimiter of `;` **and** using the `cleanup` option at the same time.
