### ISSUE TITLE
Display the points from all objects in a collection

### ISSUE THREAD

**Issue by whikloj** [Islandora-Labs/islandora_simple_map#17]
This needs to pull the entries from Solr because parsing each MODS would be too crazy. Either that or aggregate the points from all the child objects into the Collections MODS record?

I'm thinking only one level deep, again it would be too crazy otherwise. Not sure how to determine specify that a collection should display the map or not? Perhaps make it another block, then the inherent (**Show block on specific pages**) config can be used? 

My use case is migrating this Public Art map (http://umanitoba.ca/libraries/units/archfa/art_tour/) to Islandora. So I think I will also need to be able to create custom info windows, but that may have to be discussed with the collection owner.

If anyone else has a use case, please add it in and I'll keep it in mind when I am working on this.

**Comment by simonhm** [comment]
It's great if this module can display the points from all objects in a collection. One level deep should be fine enough. 
I'm using Views + Gmap to display all objects per collections.
You can try it here:   https://arch.lib.mnsu.edu/islandora/object/MSUrepository:photographs
Click on the map icon to display the map
![image](https://user-images.githubusercontent.com/6493383/28726479-028b35fe-7387-11e7-828b-78ce2cbe99df.png)
Simon.

**Comment by mjordan** [comment]
@simonhm very nice! Thanks for the example.

@whikloj if you're asking where the admin would enable a map for a particular collection, I'd recommend providing a checkbox list of collections in the Simple Map admin settings and having the admin just check the collections they want. A multi-select list might be more compact in the form, but I've found that users tend to fumble with them frequently when selecting multiple options.

**Comment by mjordan** [comment]
@whikloj SFU has two postcard collections that have geocoorindates in their MODS. I think a block like the one you show in https://github.com/mjordan/islandora_simple_map/issues/13#issuecomment-318126638 would be fine. Since there would be a lot of points on the small map, it would look very busy, but I think most users would recognize it as a map. If they wanted to put the block somewhere else where it rendered larger, they would have the option of doing so.

**Comment by whikloj** [comment]
@mjordan yeah, I think a block is probably best. If it doesn't work out once I get it built and tested, we can look at other options. We use tabs in our current interface, so I'm going to have to keep that in mind too.

**Comment by whikloj** [comment]
@mjordan This:
> I'd recommend providing a checkbox list of collections in the Simple Map admin settings ...

could be a **huge** list, it also could conflict with the block configuration for displaying on specific pages.

Perhaps it shouldn't be a block and instead it could be a checkbox on a tab inside the collection's manage tab?

**Comment by mjordan** [comment]
Agreed. I thought of inside the collection's manage tab, but the wording around what checking it does would have to be clear since it's referring to functionality configured somewhere else. Also, the checkbox should only show up if Simple Map is enabled.

**Comment by whikloj** [comment]
So I have this mostly working for collections. I did the display as a tab on the collection, otherwise I couldn't think of a good place for it.

You enable it in the main Islandora Simple Map admin. But then you have to go to the individual collection object, choose _Manage_, choose _Collection_ and then choose _Manage Islandora Simple Maps_. There you can enable the collection map.

I have a branch you can try ([issue-17](https://github.com/uml-digitalinitiatives/islandora_simple_map/tree/issue-17)), but I'm still working on adding InfoWindows to allow you to access the individual objects directly from the map.

![collection_map](https://user-images.githubusercontent.com/2857697/30399451-55ffa74c-9899-11e7-835e-351d9ecc4a0b.png)
