### ISSUE TITLE
Move variables with _mapS to _map

### ISSUE THREAD

**Issue by whikloj** [Islandora-Labs/islandora_simple_map#22]
This is my fault (again), but I added [two variables](https://github.com/mjordan/islandora_simple_map/blob/7.x/islandora_simple_map.install#L20-L21) with `islandora_simple_maps_*`.

This task is to:

1.  Change the variable name in all locations.
1. Add a `hook_update_N` task to:
     1. migrate the old variable (with S) to the new (without S) variables.
     1. Uninstall the old incorrect (with S) variables.

**Comment by mjordan** [comment]
Resolved with 7498b881ec84a94fd5bbb3fcec4da4a106835eef.
