### ISSUE TITLE
Additonal config option - expanded/collapsed?

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Labs/islandora_simple_map#3]
Could the config menu be tweaked to allow the admin to choose whether the map is expanded or collapsed by default?

**Comment by mjordan** [comment]
Yes, yes it can. The option would be site wide, i.e., not per collection or content model. Is that OK?

**Comment by mjordan** [comment]
@bondjimbond please update your 7.x branch and test. You will need to visit the admin settings page to toggle the new setting.

**Comment by bondjimbond** [comment]
Looking good! Would be nice if it were configurable per collection or per content model, but not necessary.
