### ISSUE TITLE
Not working with Thesis CModel

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Labs/islandora_simple_map#31]
Looks like this module doesn't work on objects with the Thesis CModel. Just to be sure, I've tried copying the geographic subject MODS directly from objects that do display a map - but no map on the Thesis.

**Comment by whikloj** [comment]
Anything special about the thesis object and have you tried it with the most recent commits? Just wondering if I need to back-up my version to troubleshoot this?

**Comment by whikloj** [comment]
Ok I got this, Thesis is not returning rendered HTML it is a render array. So we should be able to just append to it.

**Comment by mjordan** [comment]
Closed with f832b720ffbd3e7c9fe342ada3d804dab1cdf2ae
