### ISSUE TITLE
Compound images get 2 maps

### ISSUE THREAD

**Issue by whikloj** [Islandora-Labs/islandora_simple_map#38]
Due to the way compounds render as themselves and as their first child you get a map for each.

I have tested not allowing the rendering of the map when their is a `islandora:compoundCModel` in the `$object->models`. This makes only the map provided by the underlying `islandora:sp_large_image_cmodel` renders.

Not sure if that is okay with other users?

**Comment by mjordan** [comment]
@whikloj sounds like a reasonable approach to me. Not to complicate things, but should we provide an admin option to allow both maps to show up as they do now, with the default being the new behavior? Just a question.

**Comment by whikloj** [comment]
We certainly can. In my case all the compound parts have the same coordinates, so you get 2 identical maps. But if your compound and the first child have different coordinates then makes sense. 

Probably we should be collecting the points from the compound child items and displaying the first or all (if using Javascript API).

**Comment by mjordan** [comment]
Maybe leave it out for now. I was imagining that someone (but it's not us) had collection objects with their own geodata. If someone wants the option, we can add it later.
