### ISSUE TITLE
Last commit breaks existing implementations without reinstall - warn existing users?

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Labs/islandora_simple_map#41]
After the last time I pulled Islandora Simple Map, I could no longer access my Collections tab when managing a collection. Here's what I got in my log:

> PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'drupal.islandora_simple_map_collections_map' doesn't exist: SELECT pid from {islandora_simple_map_collections_map} WHERE pid = :pid; Array ( [:pid] => doh:root ) in _islandora_simple_map_display_collection_map() (line 201 of /opt/rh/httpd24/root/var/www/drupal7/sites/all/modules/islandora_simple_map/includes/utilities.inc).

Uninstalled the module and re-enabled it, and it works fine again. I see there's a "create table" command in the Install file that was added in December, which of course doesn't get run if you're just updating the code without reinstalling.

What would be the best way to inform users that they should uninstall and reinstall if they update their code? Google group perhaps?

**Comment by mjordan** [comment]
Does this problem persist if you run update.php (e.g., http://localhost:8000/update.php)?

**Comment by bondjimbond** [comment]
Good question! I'm not sure, 'cause I ran the uninstall and no longer have the problem.

Now of course smacking my head 'cause I should probably be running update.php every time I pull an Islandora module, just in case.

**Comment by mjordan** [comment]
@bondjimbond update.php should do it since @whikloj included an update hook in the .install file.

**Comment by whikloj** [comment]
We get so used to just pulling in the new code. I regularly forget to run `drush updatedb` with Islandora, but we should be considering a `git pull` the same as updating a module. Sorry about that @bondjimbond
