### ISSUE TITLE
Adding support for OpenStreetMap

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_simple_map#5]
I can't find much by way of a direct API for using OpenStreetMap similar to how this module uses Google Maps, but the HTML that needs to be generated looks like this:

``` html
<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://www.openstreetmap.org/export/embed.html?bbox=-123.38882446289061%2C49.14555903725487%2C-122.93563842773436%2C49.35353208188311&amp;layer=mapnik&amp;marker=49.24965507167121%2C-123.1622314453125" style="border: 1px solid black"></iframe><br/><small><a href="http://www.openstreetmap.org/?mlat=49.2497&amp;mlon=-123.1622#map=12/49.2497/-123.1622">View Larger Map</a></small>
```

The difficulty in assembling this markup is computing the `bbox` values from the lat/long. A [Perl implementation](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Lon..2Flat._to_bbox) of how to do this is available on the OSM wiki.

**Comment by MarcusBarnes** [comment]
@mjordan I'm happy to look into this time permitting.  Thanks!

**Comment by mjordan** [comment]
Excellent, thanks!

**Comment by whikloj** [comment]
This appears to be a fairly well supported library for PHP.
https://github.com/pear/Services_Openstreetmap/
