### ISSUE TITLE
Implement permission for collections with maps admin sub-tab?

### ISSUE THREAD

**Issue by whikloj** [Islandora-Labs/islandora_simple_map#50]
I was updating documentation and I realize that if you have access to the Islandora Simple Maps admin interface you can disable anyone's collection map. 

I then realized that I had half implemented this by specifying a non-existent permission to that tab.
https://github.com/mjordan/islandora_simple_map/blob/7.x/islandora_simple_map.module#L45

This task is to either change that permission to be `"administer site configuration"` like the others or implement the other permission?

@mjordan?

**Comment by mjordan** [comment]
I'd say that "administer site configuration"  is sufficient, would be for us anyway. We can always add the finer-grained permission later if someone wants it.

**Comment by whikloj** [comment]
To keep the paper trail of my stupidity consistent. I **had** already used `"administer site configuration"` as the permission and I was looking at the **access callback** not **access arguments**. 

Now I have switched the focus of this to accept the _access arguments_ in my custom access function, so when viewing the menu code it is consistent that `"administer site configuration"` is needed everywhere.

**Comment by whikloj** [comment]
As you can see on the linked PR, this was already in place I just didn't realize it.

Closing
