### ISSUE TITLE
Cache marker coordinates for collection maps

### ISSUE THREAD

**Issue by whikloj** [Islandora-Labs/islandora_simple_map#53]
When displaying huge maps (like http://digital.lib.sfu.ca/islandora/object/bcp%3Acollection/maps) the system queries for all the collection coordinates each time the map is rendered.

If we can agree on a safe way to avoid revealing objects a user doesn't have permission to see, we could cache the array which should really improve performance.

In past I have used the [users roles as a key](https://github.com/uml-digitalinitiatives/islandora_custom_solr/blob/7.x/includes/newspaper.inc#L265-L274) for the cache. So if two users have the same roles then they can share the cache entry. This only works if you **don't** assign XACML permissions based on username.

Alternatively, we could just enable a cache for anonymous users and logged in users will suffer the consequences.

**Comment by mjordan** [comment]
@whikloj I'd like to do more analysis of whether the slowdown is in the Solr query or in the rendering of the map. But I agree that it's worth increasing performance on large maps, and imperative to respect access controls. I wonder how often it is the case that we'd need to satisfy access for non-anonymous.

**Comment by whikloj** [comment]
@mjordan I am good with investigating the solr query, I'm not a Solr master and there might be things we could do to speed that up.

I'm also not really sure how many sites would need/want caching of possibly restricted materials. I think keeping this fast for anonymous visitors is more the norm.

Anyways, here is a quick and dirty cache for anonymous users.
https://github.com/mjordan/islandora_simple_map/compare/7.x...uml-digitalinitiatives:issue-53?expand=1

**Comment by mjordan** [comment]
> I'm also not really sure how many sites would need/want caching of possibly restricted materials. I think keeping this fast for anonymous visitors is more the norm.

:+1: 

I can check out your cache version tonight.

**Comment by mjordan** [comment]
@whikloj neither am I a Solr expert but thought strikes me that we might see some query speed increases if we use a filter query to limit to the collection. Filter queries are cached on the Solr side, so if there are speed increases, we may  not need to cache at the Drupal level.

**Comment by mjordan** [comment]
@whikloj the cached version is a lot faster. Check it out: http://digital.lib.sfu.ca/islandora/object/bcp%3Acollection/maps. Nice work!

**Comment by whikloj** [comment]
Cool, so should we also try moving the current [`$query`](https://github.com/mjordan/islandora_simple_map/blob/7.x/includes/utilities.inc#L367) to the `fq[]` and make the `$query = "*:*";`?

Also, should this be configurable on a collection by collection basis or should it be global but you can clear the cache on the collection's Manage -> Collection -> Manage Islandora Simple Maps tab

**Comment by mjordan** [comment]
PR #54 tested and works. I'd say a global cache is OK, no need at present to do it on a collection basis.
