### ISSUE TITLE
Modularize MODS parsing to other metadata schemas and add KML support

### ISSUE THREAD

**Issue by axfelix** [Islandora-Labs/islandora_simple_map#55]
We previously developed a module called [Islandora Gmap, or Islandora Google Maps](https://github.com/axfelix/islandora_gmap) to provide functionality for automatically embedding Google Maps on Islandora object landing pages. This module was inspired by Islandora Simple Map, and at the time provided a superset of Islandora Simple Map functionality, but Islandora Simple Map has since been made an an official Islandora Labs module. Other functionality which is of use to us -- the ability to display a single map with multiple annotations from all of its child objects on a collection landing page, to serve as an alternate entry point to the collection -- has since been added to Islandora Simple Map. Because Islandora Simple Map now has a more sustainable maintenance structure, it behooves us to merge our Islandora Gmap functionality into Simple Map.

This functionality includes:
- Modularizing the code that reads geographical coordinates out of MODS datastreams to also support DDI, or any other relevant datastream
- Displaying KML layers on Google Maps in addition to latitude/longitude coordinates.

**Comment by axfelix** [comment]
Technically another difference is that it can support reading Lat and Lon out of different fields, rather than expecting to parse them out of one: https://github.com/axfelix/islandora_gmap/blob/7.x/modules/scrape_ddi_to_gmap/scrape_ddi_to_gmap.module#L55

**Comment by axfelix** [comment]
If you're not especially keen on modularizing everything (which would be fine with me, I only want to see the functionality all working together), would it be easier to try to just incorporate everything into Simple Map as is without creating any new modules? The KML functionality in particular isn't too complex, it's basically just https://github.com/axfelix/islandora_gmap/blob/7.x/modules/kml_datastream_scrape/kml_datastream_scrape.module and this bit of added javascript: https://github.com/axfelix/islandora_simple_map/commit/26d4cc10bb70bdcdac17906032c1b2e0361b2dbb#diff-6ae360f84bcaa4cce3355d5633f0f5a7

There's a demo of that here: https://researchdata.sfu.ca/islandora/object/islandora%3A2144

**Comment by axfelix** [comment]
And for the DDI stuff, it'd just be a matter of adding a toggle around this: https://github.com/Islandora-Labs/islandora_simple_map/blob/7.x/includes/utilities.inc#L197 and incorporating the parsing-coordinates-out-of-two-fields bit into the admin form.  The only slightly messy bit would be around whether you want to hardcode a DDI option upstream (given that's otherwise not really well-supported by official Islandora modules), since trying to make it theoretically configuration-neutral around the "parsing two different XML fields" bit and the namespace would probably be more trouble than it's worth.

**Comment by axfelix** [comment]
Here's the KML stuff for a start, will let you weigh in on the DDI: https://github.com/Islandora-Labs/islandora_simple_map/pull/56

**Comment by whikloj** [comment]
@axfelix you can support your DDI use case with an implementation of the hook [`hook_islandora_simple_map_get_coordinates`](https://github.com/Islandora-Labs/islandora_simple_map/blob/7.x/islandora_simple_map.api.php#L17)

It just needs to return an array with your coordinates, how you get them is up to you. So if you want to use multiple fields or various datastreams that would all work.

Technically this array of coordinates can be anything as they are then passed to implementations of the [`hook_islandora_simple_map_parse_coordinates_callback`](https://github.com/Islandora-Labs/islandora_simple_map/blob/7.x/islandora_simple_map.api.php#L44) hook for parsing into decimal coordinates.

**Comment by axfelix** [comment]
OK, and no preference on getting this merged in with a toggle vs. being in a separate module?

**Comment by whikloj** [comment]
I have no particular preference, a separate module is probably easier. @mjordan thoughts?

**Comment by mjordan** [comment]
Separate module sounds like the way to go, that's what the hook is for. We could bundle it as a submodule, since others might find it useful.

**Comment by whikloj** [comment]
Also regarding the KML support, can you explain what kind of data you have in these custom datastreams and how you want it displayed? I am wondering if we should be parsing out the coordinates and using the standard markers or are you looking for a more custom display for these types of objects?

**Comment by axfelix** [comment]
The overlays can be quite complex, here's the example above:

https://researchdata.sfu.ca/islandora/object/islandora%3A2144

[kml.txt](https://github.com/Islandora-Labs/islandora_simple_map/files/2168092/kml.txt)

There's the datastream -- like 1.4mb of markup.

**Comment by whikloj** [comment]
So it appears that you are getting a clickable layer, does it need to be interacted with? Also do you ever have layers and markers on the same map? If so, how does that look?

**Comment by axfelix** [comment]
I don't believe we've had a more complicated example than this so far but I can test it to see what the current behaviour is ...

**Comment by axfelix** [comment]
It looks like a KML layer will totally supersede a marker right now, so only the KML is rendered if both are present.

**Comment by mjordan** [comment]
@axfelix does #59 resolve this specific issue for now? If so, can we close this one?

**Comment by axfelix** [comment]
Yup!
