### ISSUE TITLE
If multiple coordinates are given, take the first

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_simple_map#6]
For values like `+50.97583,-119.11583; +49.37833,-123.27194; +49.36667,-123.26667`, take the first point. Split on `;`.

**Comment by mjordan** [comment]
We probably should give the admin an option to define what characters to separate repeated coordinate on

**Comment by mjordan** [comment]
http://digital.lib.sfu.ca/alping-460/niut-range-camp-ridge-north-camel-mountain-aug-22-1967 is an example of repeated values.

**Comment by bondjimbond** [comment]
Would it be possible to instead plot each set of coordinates on the same map?

GMaps API supports it - e.g. https://wrightshq.com/playground/placing-multiple-markers-on-a-google-map-using-api-3/ (though this is JS, not PHP)

**Comment by whikloj** [comment]
When using the Javascript API I have it add all the points, I assumed that was desirable if possible. Also I haven't tested this 😆

**Comment by mjordan** [comment]
As long as they parse out properly, I don't see why not.

**Comment by whikloj** [comment]
Just reading the MODS page and for `coordinates` it says
> "coordinates" contains a statement of coordinates covered by the resource. One or more statements may be supplied. If one is supplied, it is a point (i.e., a single location); if two, it is a line; if more than two, it is a n-sided polygon where n=number of coordinates assigned. No three points should be co-linear, and coordinates should be supplied in polygon-traversal order.

What is not clear to me is do they mean "One or more statements may be supplied..." in the same &lt;coordinates&gt; element or as separate elements in the mods:subject?

**Comment by whikloj** [comment]
Brown University has this as an [example](http://library.brown.edu/cds/documentation/MODS_Guidelines.pdf) (page 32)
```
<mods:subject>
<mods:cartographics>
<mods:coordinates>E72°—E148°/N13°—N18°</mods:coordinates>
<mods:scale>1:22,000,00</mods:scale>
<mods:projection>Conic proj.</mods:projection>
</mods:subject>
```

**Comment by mjordan** [comment]
Yes, http://www.loc.gov/standards/mods/userguide/subject.html#coordinates is totally unclear. Not uncommon with MODS usage. If I were to make an assumption, it would be that we should expect multiple values in one `<coordinates>` element, but then we get into delimiter tangles. Not entirely sure what to do here.

**Comment by mjordan** [comment]
Just rereading my original issue here and my follow up comments (glad I commented on my own issue!),

> We probably should give the admin an option to define what characters to separate repeated coordinate on

Dunno, is that a reasonable mitigation of 'delimiter tangle'? I can add the admin option to define the delimiter after we merge your PR.

**Comment by whikloj** [comment]
I think there are two things to consider. 
1. Is what delimiter people use between coordinates and why?
2. What format the coordinates are in?

So for 1, should we assume that each coordinate is separate and individual? We could in fact use the coordinates to define a path, line or area on the map (like @uconnjeustis revealed [here](https://github.com/mjordan/islandora_simple_map/issues/7#issuecomment-229783522))
Not that the functionality is there yet, but that we could add it later so better to not paint ourselves into a corner. I'm not a GIS person, so I'm unclear what the standards are in that field.

And for 2, people's coordinates could be in multiple different formats? We could [parse other formats](https://en.wikipedia.org/wiki/Geographic_coordinate_conversion) into those used by us or we could just filter for coordinates that we can support?

**Comment by whikloj** [comment]
@mjordan bigger question, you are also allowing people to add multiple XPaths to find the coordinates. Should we follow all those paths (and split for now on `;`) and gather any coordinates we find, then de-duplicate and use 1) the first for Embed API 2) use all for Javascript API?

**Comment by whikloj** [comment]
@mjordan one more question. You are [converting](https://github.com/mjordan/islandora_simple_map/blob/7.x/islandora_simple_map.module#L167) `;` to `,`... can you remember why this was necessary and how you want to handle it in the case of splitting on `;`

**Comment by whikloj** [comment]
Ok, so I left the clean up function in and added a delimiter option. So if you set the delimiter to `;` you need to disable the clean up function. The clean-up function probably needs some review.

**Comment by whikloj** [comment]
@mjordan thanks for the examples in https://github.com/mjordan/islandora_simple_map/issues/16#issuecomment-318490252 I added the second one and discovered that I wasn't actually looping through all the coordinates. I have updated the PR to finish looping all Xpaths and processing all results found.

**Comment by whikloj** [comment]
@mjordan I think this is resolved with the merging of #20, if you are using the Embed API.

With the hook system, we stick all the coordinates in an array and [here](https://github.com/mjordan/islandora_simple_map/blob/7.x/islandora_simple_map.module#L134) we grab the first...if you are not using the Javascript API.

I'll try to test this too, but this might help to ensure that the work of #15 was subsumed by #20.

**Comment by mjordan** [comment]
@whikloj I hate to say this, but I'm getting the feeling we need to add some tests to take account of all the various ways this module can be used. I'm happy to do that work.

**Comment by whikloj** [comment]
So there are now a bunch of tests, but I'm not sure if we have alleviated your concerns. 

If yes, then I think this ticket is finished. 

If not, then I think this ticket is still finished but perhaps a new ticket for more tests is needed?

**Comment by whikloj** [comment]
@mjordan Just reviewing and this ticket can be closed.

For people using the Embed API it still generates a list of all the points but only takes the first when it renders [here](https://github.com/mjordan/islandora_simple_map/blob/7.x/islandora_simple_map.module#L168)
