### ISSUE TITLE
Add support for using the Maps JavaScript API

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_simple_map#7]
The [Google Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/) lets you create highly customized maps, including ones displaying multipoint data. This module should provide an option to use that API instead of the simple embed API.

Related issue: #6.

**Comment by uconnjeustis** [comment]
Here's an example of our bounding box information. The valuation maps was the very 1st map project that we did here at UConn. After this, we decided to record bounding box information only in mods:extension using fgdc and only record center point coordinates for mods:coordinates. We were going to find someone to convert the bounding box to center point in the future as the records have the bounding box info in both the mods:coordinates and mods:extension.

example:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<mods:mods xmlns:mods="http://www.loc.gov/mods/v3"
           xmlns:xlink="http://www.w3.org/1999/xlink"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           version="3.5"
           xsi:schemaLocation="http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-5.xsd">
   <mods:titleInfo>
      <mods:title>Ancram, New York</mods:title>
   </mods:titleInfo>
   <mods:name type="corporate"
              authority="naf"
              valueURI="http://id.loc.gov/authorities/names/n86134559">
      <mods:namePart>New York, New Haven, and Hartford Railroad Company</mods:namePart>
      <mods:role>
         <mods:roleTerm authority="marcrelator"
                        authorityURI="http://id.loc.gov/vocabulary/relators"
                        valueURI="http://id.loc.gov/vocabulary/relators/cre"
                        type="text">Creator</mods:roleTerm>
      </mods:role>
   </mods:name>
   <mods:typeOfResource>cartographic</mods:typeOfResource>
   <mods:genre authority="aat" valueURI="300028094">maps (documents)</mods:genre>
   <mods:genre authority="aat" valueURI="300264387">images (object genre)</mods:genre>
   <mods:originInfo>
      <mods:dateIssued encoding="w3cdtf" keyDate="yes">1915-06-30</mods:dateIssued>
   </mods:originInfo>
   <mods:physicalDescription>
      <mods:internetMediaType>image/jp2</mods:internetMediaType>
      <mods:digitalOrigin>reformatted digital</mods:digitalOrigin>
      <mods:note type="physical description">Source extent: 1 map ; 142 x 61 cm. 1 map ; 142 x 61 cm.</mods:note>
   </mods:physicalDescription>
   <mods:abstract>Right of way and track map Central New England Railway Co. operated by Central New England Railway Co. from Boston Corners to Campbell Hall, station 633+60 to station 686+40, town of Ancram, state of N.Y.</mods:abstract>
   <mods:targetAudience>CHO</mods:targetAudience>
   <mods:targetAudience>GEO</mods:targetAudience>
   <mods:note type="ownership">Archives &amp; Special Collections at the Thomas J. Dodd Research Center, University of Connecticut Libraries</mods:note>
   <mods:note type="source note">New York, New Haven, and Hartford Railroad Company Valuation Maps Collection</mods:note>
   <mods:note>Bounding box coordinates recorded as S, W, N, E</mods:note>
   <mods:subject>
      <mods:topic>Railroads</mods:topic>
      <mods:geographic>Ancram (N.Y.)</mods:geographic>
      <mods:geographic>New York</mods:geographic>
      <mods:cartographics>
         <mods:coordinates>42.009774, -73.589991, 42.024636, -73.568928</mods:coordinates>
      </mods:cartographics>
   </mods:subject>
   <mods:identifier type="local">Roll no. 294</mods:identifier>
   <mods:identifier type="local">Valuation no. 80.87, sheet 7</mods:identifier>
   <mods:identifier type="local">Accession number MSS1998-0378</mods:identifier>
   <mods:identifier type="local">uconn_asc_1998_0378_map_80_87_7.tif</mods:identifier>
   <mods:accessCondition type="use and reproduction">These Materials are provided for educational and research purposes only. The University of Connecticut Libraries hold the copyright except where noted. Permission must be obtained in writing from the University of Connecticut Libraries and/or the owner(s) of the copyright to publish reproductions or quotations beyond "fair use."</mods:accessCondition>
   <mods:accessCondition type="restrictions on access">The collection is open and available for research.</mods:accessCondition>
   <mods:extension xmlns:fgdc="http://www.fgdc.gov/schemas/metadata/fgdc-std-001-1998.xsd">
      <fgdc:metadata>
         <fgdc:idinfo>
            <fgdc:spdom>
               <fgdc:bounding>
                  <fgdc:westbc>-73.589991</fgdc:westbc>
                  <fgdc:eastbc>-73.568928</fgdc:eastbc>
                  <fgdc:northbc>42.024636</fgdc:northbc>
                  <fgdc:southbc>42.009774</fgdc:southbc>
               </fgdc:bounding>
            </fgdc:spdom>
         </fgdc:idinfo>
      </fgdc:metadata>
   </mods:extension>
   <mods:recordInfo>
      <mods:recordContentSource>University of Connecticut Libraries</mods:recordContentSource>
      <mods:recordCreationDate encoding="w3cdtf">2015-04-07-04:00</mods:recordCreationDate>
      <mods:languageOfCataloging>
         <mods:languageTerm authority="iso639-2b" type="code">eng</mods:languageTerm>
      </mods:languageOfCataloging>
      <mods:recordOrigin>This MODS record was migrated from University of Connecticut Libraries Archives and Special Collections CONTENTdm site. . Other information: MJB</mods:recordOrigin>
   </mods:recordInfo>
</mods:mods>
```

**Comment by mjordan** [comment]
After some work over the weekend in the [issue-7 branch](https://github.com/mjordan/islandora_simple_map/tree/issue-7), I've discovered that it's not trivial, if possible at all, to use the Google Maps JavaScript API within existing Drupal themes, since _all_ of the ancestors of the `<div>` containing the map need to have an explicit CSS property of `height: 100%`. It's easy enough to add this to markup generated by this module, and we can even add it to existing `<div id="page-wrapper">`, `<div id="page">`, `<div id="main-wrapper">`, `<div id="main">`, etc. all the way from `<html>` down to the map's `<div>`. But, to do that, we need to assume that all themes use the same div IDs all the way down, and that the HTML containing the map has not been overridden locally using standard Drupal theming techniques.  Those are likely not safe assumptions. 

Evidence that has led me to this conclusion about the required CSS is the following [passage](https://developers.google.com/maps/documentation/javascript/tutorial#The_Hello_World_of_Google_Maps_v3) from the API documentation:

> Note that some CSS that works within quirks mode is not valid in standards mode. In specific, all percentage-based sizes must inherit from parent block elements, and if any of those ancestors fail to specify a size, they are assumed to be sized at 0 x 0 pixels.

I've confirmed my understanding of "any of those ancestors" by using the following HTML to render a map via the API:

``` html
  <div style="height:100%">
    <div id="map"></div>
  </div>
```

If the outer `<div>` is a child of `<html>` and `<body>` with CSS `height: 100%` applied (in other words, all ancestors have a CSS height of 100%), the map shows up; if I add an additional wrapping `<div>` without `height: 100%` being explicitly set (in other words, introduce an ancestor that doesn't have a 100% height), the map does not show up.

I'll leave this issue open in the hopes that someone can suggest a viable path forward. But, unless we can figure out how we might add the required CSS all the way down the tree safely, this module will probably not be able to support the Google Maps JavaScript API, and therefore not render anything other than maps with a single point on them.

**Comment by uconnjeustis** [comment]
Mark et al.,
I'm fine with the single center points that the simple map does currently. There was work on how to display GIS materials - it was an interest group. Perhaps this can be resurrected if there's enough interest.

And thanks for doing all this work and investigation. The simple map is already installed and we're so happy with it.

Jennifer

**Comment by whikloj** [comment]
@mjordan I think the problem you were experiencing is that if the DIV is collapsed, Google doesn't load its tiles. But it also doesn't recognize the expansion as a resize or change. Instead you need to refresh the map to be aware of the new viewport. 

I have a large PR coming.

**Comment by mjordan** [comment]
@whikloj nice work on that stumper, adding support for the full API to this module opens up a lot of possibilities. Thanks, as always.

**Comment by whikloj** [comment]
@mjordan I think this can be closed, new features can be opened as a new ticket. But you now have Javascript API support. 👍

**Comment by mjordan** [comment]
Very nice, thank you @whikloj for your tremendous work on this module!
